Repository ArkEcosystem/rust-crypto, pull requests merged in 2019-05, with the labels that each got.

#23 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#24 style: make clippy happy
  src/identities/private_key.rs
  src/identities/public_key.rs
  src/lib.rs
  src/transactions/deserializer.rs
  src/transactions/transaction.rs
  src/utils/message.rs
Labels: Complexity: Low, Type: Refactor

#25 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
